name: test_cookieproj_rtd

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>=3.6
    - anaconda
    - astropy
    - sphinx >= 1.6
    - pip
    - pip:
        - GitPython
        - configparser
        - sphinx-astropy
        - sphinx_rtd_theme
