name: test_cookieproj_rtd

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>=3.6
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas
    - matplotlib
    - scipy
    - seaborn
    - sphinx >= 1.6
    - pip
    - pip:
        - GitPython
        - sphinx_rtd_theme
        - cosmo-utils
        - configparser
        - sphinx-astropy
        - numpydoc
