name: test_cookieproj_rtd

channels:
  - defaults

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
  - seaborn
  - sphinx >= 1.6
  - pip
  - pip:
    - GitPython
    - progressbar2
    - sphinx_rtd_theme
    - cosmo-utils
    - configparser
    - sphinx-astropy
    - numpydoc
